.TH cat
.SH Summary
cat is most often used just to print a file to the terminal.
.br
For a short file, it's the quickest way to read the contents.
.br
More precisely, it concatenates one or more inputs to standard output.
.SH Basics
.B "cat brevity.txt"
.br
Prints the contents of the file 
.I brevity.txt
to the terminal. This assumes brevity.txt is in our current directory.
