.TH FIND
.SH Summary
.B find
is used to find files.
.br
Use the parameters to fill out details of what you want to find.
.br
It is common to 'pipe' the output to another utility. See Advanced section.
.br
Find is a complex command. The man page is extensive.

.SH Basics
.B "$ find . -name \(dq*.txt\(dq"
.br
Find any files ending in '.txt' in the current directory
.br
N.B. This will recurse into sub-directories by default.

.B "$ find /etc -type f"
.br
Find anything of type 'file' in the /etc directory (so: ignore directories inside /etc)

.B "$ find /etc -type d"
.br
Find anything of type 'directory' in the /etc directory (so: ignore files inside /etc)

.SH Advanced
.B "$ find . -name *.txt" | exec -md5sum {} \\\;
.br
Find any files or directories ending in *.txt in the current directory and calculate their md5sum
