.TH git
.SH Summary
git is a version control system. 
.br
Using it requires some knowledge of the underlying data model 
.SH Basics
.B "git status"
.br
Shows the status of the repository in which you are located.
.br
.B "git diff"
.br
Shows the diff between the working directory and the most recent commit
.br
.B "git diff --staged"
.br
Shows the changes you would commit, if you subsequently run 
.br
.B "git commit"
.br
This command creates a new commit. It is appended to whatever branch you are in.
